[package]
name = "clock"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.23"
egui = "0.23"
chrono = { version = "0.4", features = ["clock"] }
rodio = "0.17"
notify-rust = "4.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
image = "0.25.6"

